package k6metricset

type AutoGenerated struct {
	Data struct {
		ID         string `json:"id"`
		Attributes struct {
			Sample struct {
				Avg   float64 `json:"avg"`
				Max   float64 `json:"max"`
				Med   float64 `json:"med"`
				Min   float64 `json:"min"`
				P90   float64 `json:"p(90)"`
				P95   float64 `json:"p(95)"`
				Count int     `json:"count"`
				Value int     `json:"value"`
				Rate  float64 `json:"rate"`
			} `json:"sample"`
		} `json:"attributes"`
	} `json:"data"`
}
